name: 'version'
description: 'GitHub action helper: version'

outputs:
  version:
    description: The version found for the requested type
    value: ${{ steps.version.outputs.version }}
runs:
  using: composite
  steps:
    - shell: bash
      id: version
      env:
        GITHUB_EVENT_INPUTS_VERSION: ${{ github.event.inputs.version }}
        GITHUB_EVENT_INPUTS_STABLE: ${{ github.event.inputs.stable }}
        INPUTS_TYPE: ${{ inputs.type }}
        EVENT_NAME: ${{ github.event_name }}
        REF: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}
        UV_SYSTEM_PYTHON: "true"
      run: |
        version=$(echo "$REF" | awk -F"/" '{print $NF}' )
        echo "VERSION: ${version}"
        base_ver=$(grep "homeassistant" requirements.txt | awk -F"==" '{print $2}')
        if [[ "${version}" == "master" ]]; then
          if tag="$(git describe --tags --abbrev=0 --match="${base_ver}.*" 2>/dev/null)"; then 
            final_ver="$(echo $tag | awk -F. '{printf "%s.%s.%s.%d",$1,$2,$3,$4+1}'}""
          else
            final_ver="${base_ver}.0"
          fi    
        elif [[ "${version}" == "dev" || "${version}" == "automation" ]]; then
          if tag="$(git describe --tags --abbrev=0 --match="${base_ver}_${version}.*" 2>/dev/null)"; then 
            final_ver="$(echo $tag | awk -F. '{printf "%s.%s.%s.%d",$1,$2,$3,$4+1}')"
          else
            final_ver="${base_ver}_${version}.0"
          fi    
        fi

        echo "VERSION: ${final_ver}"

        echo "version=${final_ver}" >> "$GITHUB_OUTPUT"
