name: Update module

inputs:
  version:
    description: The version to update to
    required: true
runs:
  using: composite
  steps:
    - name: "Check out repository"
      uses: "actions/checkout@v4"
      with:
        ref: master
    - shell: bash
      run: |
        git checkout -b ${{ inputs.version }}
        ./update.sh ${{ inputs.version }}
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update to ${{ inputs.version }}"
        git push origin ${{ inputs.version }}
