name: Debugging
on:
  workflow_call:
  workflow_dispatch:

    
jobs:
  check_out:
    uses: "actions/checkout@v4"
  version:
    uses: "catjw/ha-smartthings-smooples/.github/workflows/helpers/version.yaml@dev"
    with:
      core_version: "2023.9.0"