name: Debugging
on:
  workflow_call:
  workflow_dispatch:

    
jobs:
  get_version:
    name: "Get version"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Get version"
        id: "version"
        uses: "./.github/actions/version.yaml@dev"
        with:
          core_version: "2023.9.0"
