name: Debugging
on:
  workflow_call:
  workflow_dispatch:

    
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Get version"
        id: "version"
        uses: "catjw/ha-smartthings-smooples/.github/actions/version.yaml@dev"
        with:
          core_version: "2023.9.0"