name: Automatically create / update pull request

# run this workflow only on new feature branches, not when they're merged to main
on:
  push:
    branches-ignore:
      - master
      - dev
      - automation
jobs:
  push-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: automation
          persist-credentials: false
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: ${{ github.ref }}
          target: 'automation'
          webhook_url: #if present add the Slack webhook
