name: Push

on:
  push:
    branches:
      - master
      - dev

jobs:
  hassfest:
    uses: catjw/ha-smartthings-smooples/.github/workflows/hassfest.yaml@master
    needs: [tests]
  hacs-validate:
    uses: catjw/ha-smartthings-smooples/.github/workflows/validate.yaml@master
    needs: [tests]
