name: Push

on:
  push:
    branches:
      - master
      - dev

jobs:
  # tests:
  #   uses: catjw/ha-smartthings-smooples/.github/workflows/tests.yaml@master
  # hassfest:
  #   uses: catjw/ha-smartthings-smooples/.github/workflows/hassfest.yaml@master
  #   needs: [tests]
  # hacs-validate:
  #   uses: catjw/ha-smartthings-smooples/.github/workflows/validate.yaml@master
  #   needs: [tests]
  version:
    uses: catjw/ha-smartthings-smooples/.github/workflows/version.yaml@master
    # needs: [hassfest, hacs-validate]