name: Push

on:
  push:
    branches:
      - master
      - dev

jobs:
  hassfest:
    uses: catjw/ha-smartthings-smooples/.github/workflows/hassfest.yaml@master
  hacs-validate:
    uses: catjw/ha-smartthings-smooples/.github/workflows/validate.yaml@master
  # release:
  #   uses: catjw/ha-smartthings-smooples/.github/workflows/release.yaml@master
  #   needs: [hassfest, hacs-validate]