name: Push

on:
  push:
    branches:
      - master
      - dev

jobs:
  tests:
    uses: catjw/ha-smartthings-smooples/.github/workflows/tests.yaml@master
  hassfest:
    uses: catjw/ha-smartthings-smooples/.github/workflows/hassfest.yaml@master
    needs: [tests]
  hacs-validate:
    uses: catjw/ha-smartthings-smooples/.github/workflows/validate.yaml@master
    needs: [tests]
  update-hacs-manifest:
    uses: catjw/ha-smartthings-smooples/.github/workflows/update_hacs_manifest.yaml@dmaster
    needs: [hassfest, hacs-validate]
  # release:
  #   uses: catjw/ha-smartthings-smooples/.github/workflows/release.yaml@master
  #   needs: [update-hacs-manifest]