name: Push

on:
  push:
    branches:
      - master
      - dev

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    outputs:
      current: ${{ steps.current.outputs.version }}
      latest: ${{ steps.latest.outputs.version }}
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: Get current version
        id: current
        run: |
          current_ver=$(grep "homeassistant" requirements.txt | awk -F"==" '{print $2}')
          echo "version=${current_ver}" >> $GITHUB_OUTPUT
      - name: Setup Python
        uses: "actions/setup-python@v4.7.0"
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get latest Version
        id: latest
        run: |
          python3 -m pip list --outdated | grep ^homessistant | awk '{print $3}'
          latest=$(python3 -m pip list --outdated | grep ^homessistant | awk '{print $3}')
          echo "version=${latest}" >> $GITHUB_OUTPUT
      - name: Compare versions
        id: compare
        run: |
          echo "${{ join(steps.current.outputs.*, '\n') }}"
          echo "${{ join(steps.latest.outputs.*, '\n') }}"
          if [ "${{ steps.current.outputs.version }}" != "${{ steps.latest.outputs.version }}" ]; then
            echo "Versions are different"
            echo "version=${{ steps.latest.outputs.version }}" >> "$GITHUB_OUTPUT"
          else
            echo "Versions are the same"
            echo "version=${{ steps.current.outputs.version }}" >> "$GITHUB_OUTPUT"
          fi
  # tests:
  #   uses: catjw/ha-smartthings-smooples/.github/workflows/tests.yaml@dev
  # hassfest:
  #   uses: catjw/ha-smartthings-smooples/.github/workflows/hassfest.yaml@master
  #   needs: [tests]
  # hacs-validate:
  #   uses: catjw/ha-smartthings-smooples/.github/workflows/validate.yaml@master
  #   needs: [tests]
  # update-hacs-manifest:
  #   uses: catjw/ha-smartthings-smooples/.github/workflows/update_hacs_manifest.yaml@master
  #   needs: [hassfest, hacs-validate]
  # release:
  #   uses: catjw/ha-smartthings-smooples/.github/workflows/release.yaml@master
  #   needs: [update-hacs-manifest]