name: Release

on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  release:
    # if: ${{ github.repository_owner == 'BottlecapDave' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta') }}
    needs: 
    - validate
    # - unit_tests
    # - integration_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: asdf_install
        uses: asdf-vm/actions/install@v3
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
      - name: Merge main into develop
        if: ${{ github.repository_owner == 'BottlecapDave' && github.ref == 'refs/heads/main' }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: "chore: Merged main into develop"
          from_branch: main
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge main into beta
        if: ${{ github.repository_owner == 'BottlecapDave' && github.ref == 'refs/heads/beta' }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: "chore: Merged main into beta"
          from_branch: main
          target_branch: beta
          github_token: ${{ secrets.GITHUB_TOKEN }}