name: Push

on:
  push:
    branches:
      # - master
      - dev

jobs:
  debugging:
    uses: "catjw/ha-smartthings-smooples/.github/workflows/helpers/version.yaml@dev"
    with:
      core_version: "2023.9.0"
