name: Update HACS manifest

on:
  workflow_call:
  workflow_dispatch:

jobs:
  update-hacs-manifest:
    name: "Update HACS manifest and Tag"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"

      - name: "Get current version"
        shell: "bash"
        run: |
          echo "CURRENT_VERSION=$(yq '.version' ${{ github.workspace }}/custom_components/smartthings/manifest.json)" >> $GITHUB_ENV

      - name: "Get version"
        id: "version"
        uses: "home-assistant/actions/helpers/version@master"
      - uses: "actions/checkout@v4"
      - name: "Set and commit manifest version number"
        shell: "bash"
        if: ${{ !contains(steps.version.outputs.version, $CURRENT_VERSION) }}
        run: |
          yq -i -o json '.version="${{ steps.version.outputs.version }}"' \
            "${{ github.workspace }}/custom_components/smartthings/manifest.json"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${{ github.workspace }}/custom_components/smartthings/manifest.json"
          git commit -m "Update version to ${{ steps.version.outputs.version }}"
          git push

      - name: "Tag"
        run: |
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git push
