name: Update HACS manifest

on:
  workflow_call:
  workflow_dispatch:

jobs:
  update-hacs-manifest:
    name: "Prepare release asset"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
        with:
          ref: ${{ github.ref }}

      - name: "Get version"
        id: "version"
        uses: "home-assistant/actions/helpers/version@master"

      - name: "Set manifest version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ steps.version.outputs.version }}"' \
            "${{ github.workspace }}/custom_components/smartthings/manifest.json"

      - uses: "actions/checkout@v4"
      - name: "Commit and tag"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git status
          git add "${{ github.workspace }}/custom_components/smartthings/manifest.json"
          git commit --amend --no-edit
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git push
      # git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
      # git config --global user.name "$GITHUB_ACTOR"
      # git add ${{ github.workspace }}/custom_components/smartthings/manifest.json
      # git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
      # git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tags


      - name: "Print Envs"
        run: |
          echo ${{ github.event.inputs }}
          echo ${{ github.event.inputs.version }}
          echo ${{ steps.version.outputs.version }}
          echo ${{ steps.version.outputs.stable }}
          echo ${{ github.event_name }}
          echo ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}
          yq '.version' ${{ github.workspace }}/custom_components/smartthings/manifest.json

      - name: "Create zip"
        run: |
          cd custom_components/smartthings
          zip smartthings.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ github.workspace }}/custom_components/smartthings/smartthings.zip