name: Update HACS manifest

on:
  workflow_call:
  workflow_dispatch:

jobs:
  update-hacs-manifest:
    name: "Prepare release asset"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"

      - name: "Get version"
        id: "version"
        uses: "home-assistant/actions/helpers/version@master"

      - name: "Set manifest version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ steps.version.outputs.version }}"' \
            "${{ github.workspace }}/custom_components/smartthings/manifest.json"

      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config --global user.name "$GITHUB_ACTOR"

      - name: "Version Push"
        id: "version-push"
        uses: "home-assistant/actions/helpers/version-push@master"
        with:
          key: version
          version: ${{ steps.version.outputs.version }}


      - name: "Print Envs"
        run: |
          echo ${{ github.event.inputs }}
          echo ${{ github.event.inputs.version }}
          echo ${{ steps.version.outputs.version }}
          echo ${{ steps.version.outputs.stable }}
          echo ${{ github.event_name }}
          echo ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}
          yq '.version' ${{ github.workspace }}/custom_components/smartthings/manifest.json

      - name: "Create zip"
        run: |
          cd custom_components/smartthings
          zip smartthings.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ github.workspace }}/custom_components/smartthings/smartthings.zip