name: Update HACS manifest

on:
  workflow_call:
  workflow_dispatch:

jobs:
  update-hacs-manifest:
    name: "Update HACS manifest and Tag"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Get version"
        id: "version"
        uses: "home-assistant/actions/helpers/version@master"

      - uses: "actions/checkout@v4"
      - name: "Set and commit manifest version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ steps.version.outputs.version }}"' \
            "${{ github.workspace }}/custom_components/smartthings/manifest.json"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${{ github.workspace }}/custom_components/smartthings/manifest.json"
          git diff --quiet && git diff --staged --quiet || git commit -m "Update version to ${{ steps.version.outputs.version }}"
          git push

      - name: "Tag"
        run: |
          git tag -d ${{ steps.version.outputs.version }} || true
          git push origin :refs/tags/${{ steps.version.outputs.version }} || true
          git tag -fa ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git push origin --tags
