name: Version Increment

on:
  workflow_call:
  workflow_dispatch:

jobs:
  get-version:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v3.5.3"
      - name: "Get current version"
        id: current
        shell: bash
        run: |
          echo "VERSION=$(yq -o json '.version' ${{ github.workspace }}/custom_components/smartthings/manifest.json)" >> $GITHUB_OUTPUT
    outputs:
      VERSION: ${{steps.current.outputs.VERSION}}
  new-version:
    needs: get-version
    with:
      VERSION: ${{ needs.get-version.outputs.VERSION }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v3.5.3"
      - name: "Adjust version number"
        shell: "bash"
        run: |
          echo "NEW_VERSION=$($VERSION | awk -F'.' '{print $1 "." $2 "." $3+=1}')" >> $GITHUB_OUTPUT
      - name: "Adjust version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/smartthings/manifest.json"

      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"
      - run: git tag ${VERSION}
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tags